### ISSUE TITLE
Add support for Obsidian.md comment syntax

### ISSUE THREAD

**Issue by mkusz** [mkusz/mkdocs-publisher#46]
### Feature description

Basic syntax of Obsidian.md flavored Markdown allows adding comments (block and inline) by using `%%` opening and closing symbols. Example:

```markdown
This is an %%inline%% comment.

%%
This is a block comment.

Block comments can span multiple lines.
%%
```

### Project plugin

- [ ] pub-blog
- [ ] pub-debugger
- [ ] pub-meta
- [ ] pub-minifier
- [X] pub-obsidian
- [ ] pub-social
- [ ] a new plugin
- [ ] external plugin integration

### Link

https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Comments

**Comment by AgedLace** [comment]
This is working in version 1.2.0.
