### ISSUE TITLE
Add support for Obsidian.md mix of ordered and unordered lists

### ISSUE THREAD

**Issue by mkusz** [mkusz/mkdocs-publisher#48]
### Future description

Basic syntax of Obsidian.md flavored Markdown allows for creating a mix of ordered and unordered lists.

### Project plugin

- [ ] pub-blog
- [ ] pub-debugger
- [ ] pub-meta
- [ ] pub-minifier
- [X] pub-obsidian
- [ ] pub-social
- [ ] a new plugin
- [ ] external plugin integration

### Link

https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Lists

**Comment by AgedLace** [comment]
I haven't had time to check yet, but might be helpful to let people know in the documentation that Outliner plugin prevents mixed lists.  

I have a several more things to take care of, then I'll be turning my attention to the latest version / updates.  

THANK YOU!

**Comment by mkusz** [comment]
When I will implement it, will add this information, but to be honest, it's not a thing that is related to this project. It's a pure Obsidian problem, and if syntax is correct, Outliner plugin will not affect display of the mixed lists here.

**Comment by AgedLace** [comment]
You are right - it's really not related to your project.

This works in version 1.2.0.

**Comment by mkusz** [comment]
So it seems like I didn't test it before writing this future request. It seems like it's supported out off the box, but it works a bit different than described in the linked documentation:

Obsidian:
```
1. First list item
    1. Ordered nested list item
2. Second list item
    - Unordered nested list item
3. Third point
    1. Sub level to point 3
        1. Just another sub level
```

MkDocs produced from the above Obsidian input:
```
1. First list item
    a. Ordered nested list item
2. Second list item
    - Unordered nested list item
3. Third point
    a. Sub level to point 3
        i. Just another sub level
```

Seems like this request was not needed.

**Comment by AgedLace** [comment]
I've tested multi-mixed (ordered -> unordered -> ordered), and it works exactly as expected.

**Comment by AgedLace** [comment]
I retested this ... 

In Obsidian 

```
1. First list item
	 1. Ordered nested list item
2. Second list item
	 * Unordered nested list item
* Unordered List Item
	 1. Ordered nested list
3. Third Ordered list Item
	- Unordered nested 
```

MkDocs output 

```
1. First list item
     a. Ordered nested list item
2. Second list item
    - Unordered nested list item
3. Unordered List Item
    a. Ordered nested list
4. Third Ordered list Item
    - Unordered nested
```

**Comment by mkusz** [comment]
Yes, the output is different but to be honest, what is a meaning of injecting an unordered list element inside ordered one at the same level? In real live, when something like this happen you would rather do something like this:
```
1. First list item
	1. Ordered nested list item
2. Second list item
	* Unordered nested list item
	* Unordered List Item
3. Third Ordered list Item
	- Unordered nested 
```
or something like this:
```
1. First list item
	1. Ordered nested list item
2. Second list item
	* Unordered nested list item

Some text:

* Unordered List Item
	1. Ordered nested list

Just another list:

1. Third Ordered list Item
	- Unordered nested 
```
I don't feel like this is something crucial at this point.

**Comment by mkusz** [comment]
I dig a bit deeper into this and there is a markdown extensions called [sane-list](https://python-markdown.github.io/extensions/sane_lists/). When you add it to the markdown extensions config in `mkdocs.yml` file, you can achieve this behaviour:
```yaml
markdown_extensions:
  - sane_lists
```

List example (you need to add an empty line in beetween ordered an unorded alements at the same indentation level):
```markdown
1. First list item
    1. Ordered nested list item
2. Second list item
    * Unordered nested list item

* Unordered List Item
    1. Ordered nested list

3. Third Ordered list Item
    - Unordered nested 
```

**Comment by AgedLace** [comment]
Thank you - I will add that markdown extension.
